module.exports.DATE_FORMAT = "YYYY/MM/DD";
module.exports.TIME_HOUR_AND_MINUTE = "HH:mm";
module.exports.DATE_FORMAT_AND_TIME = "YYYY/MM/DD HH:mm:ss";
module.exports.SEATS = [
    [
      { code: 'A1', seatClass: 'VIP' },
      { code: 'A2', seatClass: 'VIP' },
      { code: 'A3', seatClass: 'VIP' },
      { code: 'A4', seatClass: 'VIP' },
      { code: 'A5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'A6', seatClass: 'VIP' },
      { code: 'A7', seatClass: 'VIP' },
      { code: 'A8', seatClass: 'VIP' },
      { code: 'A9', seatClass: 'VIP' },
      { code: 'A10', seatClass: 'VIP' },
      { code: 'A11', seatClass: 'VIP' },
      { code: 'A12', seatClass: 'VIP' },
      { code: 'A13', seatClass: 'VIP' },
      { code: 'A14', seatClass: 'VIP' },
    ],
    [
      { code: 'B1', seatClass: 'VIP' },
      { code: 'B2', seatClass: 'VIP' },
      { code: 'B3', seatClass: 'VIP' },
      { code: 'B4', seatClass: 'VIP' },
      { code: 'B5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'B6', seatClass: 'VIP' },
      { code: 'B7', seatClass: 'VIP' },
      { code: 'B8', seatClass: 'VIP' },
      { code: 'B9', seatClass: 'VIP' },
      { code: 'B10', seatClass: 'VIP' },
      { code: 'B11', seatClass: 'VIP' },
      { code: 'B12', seatClass: 'VIP' },
      { code: 'B13', seatClass: 'VIP' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'C1', seatClass: 'VIP' },
      { code: 'C2', seatClass: 'VIP' },
      { code: 'C3', seatClass: 'VIP' },
      { code: 'C4', seatClass: 'VIP' },
      { code: 'C5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'C6', seatClass: 'VIP' },
      { code: 'C7', seatClass: 'VIP' },
      { code: 'C8', seatClass: 'VIP' },
      { code: 'C9', seatClass: 'VIP' },
      { code: 'C10', seatClass: 'VIP' },
      { code: 'C11', seatClass: 'VIP' },
      { code: 'C12', seatClass: 'VIP' },
      { code: 'C13', seatClass: 'VIP' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'D1', seatClass: 'VIP' },
      { code: 'D2', seatClass: 'VIP' },
      { code: 'D3', seatClass: 'VIP' },
      { code: 'D4', seatClass: 'VIP' },
      { code: 'D5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'D6', seatClass: 'VIP' },
      { code: 'D7', seatClass: 'VIP' },
      { code: 'D8', seatClass: 'VIP' },
      { code: 'D9', seatClass: 'VIP' },
      { code: 'D10', seatClass: 'VIP' },
      { code: 'D11', seatClass: 'VIP' },
      { code: 'D12', seatClass: 'VIP' },
      { code: 'D13', seatClass: 'VIP' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'E1', seatClass: 'VIP' },
      { code: 'E2', seatClass: 'VIP' },
      { code: 'E3', seatClass: 'VIP' },
      { code: 'E4', seatClass: 'VIP' },
      { code: 'E5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'E6', seatClass: 'VIP' },
      { code: 'E7', seatClass: 'VIP' },
      { code: 'E8', seatClass: 'VIP' },
      { code: 'E9', seatClass: 'VIP' },
      { code: 'E10', seatClass: 'VIP' },
      { code: 'E11', seatClass: 'VIP' },
      { code: 'E12', seatClass: 'VIP' },
      { code: 'E13', seatClass: 'VIP' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'F1', seatClass: 'VIP' },
      { code: 'F2', seatClass: 'VIP' },
      { code: 'F3', seatClass: 'VIP' },
      { code: 'F4', seatClass: 'VIP' },
      { code: 'F5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'F6', seatClass: 'VIP' },
      { code: 'F7', seatClass: 'VIP' },
      { code: 'F8', seatClass: 'VIP' },
      { code: 'F9', seatClass: 'VIP' },
      { code: 'F10', seatClass: 'VIP' },
      { code: 'F11', seatClass: 'VIP' },
      { code: 'F12', seatClass: 'VIP' },
      { code: 'F13', seatClass: 'VIP' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'G1', seatClass: 'VIP' },
      { code: 'G2', seatClass: 'VIP' },
      { code: 'G3', seatClass: 'VIP' },
      { code: 'G4', seatClass: 'VIP' },
      { code: 'G5', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'G6', seatClass: 'VIP' },
      { code: 'G7', seatClass: 'VIP' },
      { code: 'G8', seatClass: 'VIP' },
      { code: 'G9', seatClass: 'VIP' },
      { code: 'G10', seatClass: 'VIP' },
      { code: 'G11', seatClass: 'VIP' },
      { code: 'G12', seatClass: 'VIP' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'H1', seatClass: 'A' },
      { code: 'H2', seatClass: 'A' },
      { code: 'H3', seatClass: 'A' },
      { code: 'H4', seatClass: 'A' },
      { code: 'H5', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'H6', seatClass: 'A' },
      { code: 'H7', seatClass: 'A' },
      { code: 'H8', seatClass: 'A' },
      { code: 'H9', seatClass: 'A' },
      { code: 'H10', seatClass: 'A' },
      { code: 'H11', seatClass: 'A' },
      { code: 'H12', seatClass: 'A' },
      { code: 'H13', seatClass: 'A' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'I1', seatClass: 'A' },
      { code: 'I2', seatClass: 'A' },
      { code: 'I3', seatClass: 'A' },
      { code: 'I4', seatClass: 'A' },
      { code: 'I5', seatClass: 'A' },
      { code: 'I6', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'I7', seatClass: 'A' },
      { code: 'I8', seatClass: 'A' },
      { code: 'I9', seatClass: 'A' },
      { code: 'I10', seatClass: 'A' },
      { code: 'I11', seatClass: 'A' },
      { code: 'I12', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'K1', seatClass: 'A' },
      { code: 'K2', seatClass: 'A' },
      { code: 'K3', seatClass: 'A' },
      { code: 'K4', seatClass: 'A' },
      { code: 'K5', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'K6', seatClass: 'A' },
      { code: 'K7', seatClass: 'A' },
      { code: 'K8', seatClass: 'A' },
      { code: 'K9', seatClass: 'A' },
      { code: 'K10', seatClass: 'A' },
      { code: 'K11', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'L1', seatClass: 'A' },
      { code: 'L2', seatClass: 'A' },
      { code: 'L3', seatClass: 'A' },
      { code: 'L4', seatClass: 'A' },
      { code: 'L5', seatClass: 'A' },
      { code: 'L6', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'L7', seatClass: 'A' },
      { code: 'L8', seatClass: 'A' },
      { code: 'L9', seatClass: 'A' },
      { code: 'L10', seatClass: 'A' },
      { code: 'L11', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'M1', seatClass: 'A' },
      { code: 'M2', seatClass: 'A' },
      { code: 'M3', seatClass: 'A' },
      { code: 'M4', seatClass: 'A' },
      { code: 'M5', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'M6', seatClass: 'A' },
      { code: 'M7', seatClass: 'A' },
      { code: 'M8', seatClass: 'A' },
      { code: 'M9', seatClass: 'A' },
      { code: 'M10', seatClass: 'A' },
      { code: 'M11', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'N1', seatClass: 'A' },
      { code: 'N2', seatClass: 'A' },
      { code: 'N3', seatClass: 'A' },
      { code: 'N4', seatClass: 'A' },
      { code: 'N5', seatClass: 'A' },
      { code: 'N6', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'N7', seatClass: 'A' },
      { code: 'N8', seatClass: 'A' },
      { code: 'N9', seatClass: 'A' },
      { code: 'N10', seatClass: 'A' },
      { code: 'N11', seatClass: 'A' },
      { code: 'N12', seatClass: 'A' },
      { code: 'N13', seatClass: 'A' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'O1', seatClass: 'B' },
      { code: 'O2', seatClass: 'B' },
      { code: 'O3', seatClass: 'B' },
      { code: 'O4', seatClass: 'B' },
      { code: 'O5', seatClass: 'B' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'O6', seatClass: 'B' },
      { code: 'O7', seatClass: 'B' },
      { code: 'O8', seatClass: 'B' },
      { code: 'O9', seatClass: 'B' },
      { code: 'O10', seatClass: 'B' },
      { code: 'O11', seatClass: 'B' },
      { code: 'O12', seatClass: 'B' },
      { code: 'O13', seatClass: 'B' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'P1', seatClass: 'B' },
      { code: 'P2', seatClass: 'B' },
      { code: 'P3', seatClass: 'B' },
      { code: 'P4', seatClass: 'B' },
      { code: 'P5', seatClass: 'B' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
      { code: 'P6', seatClass: 'B' },
      { code: 'P7', seatClass: 'B' },
      { code: 'P8', seatClass: 'B' },
      { code: 'P9', seatClass: 'B' },
      { code: 'P10', seatClass: 'B' },
      { code: 'P11', seatClass: 'B' },
      { code: 'P12', seatClass: 'B' },
      { code: 'P13', seatClass: 'B' },
      { code: 'BLOCK' },
    ],
    [
      { code: 'Q1', seatClass: 'B' },
      { code: 'Q2', seatClass: 'B' },
      { code: 'Q3', seatClass: 'B' },
      { code: 'Q4', seatClass: 'B' },
      { code: 'Q5', seatClass: 'B' },
      { code: 'Q6', seatClass: 'B' },
      { code: 'Q7', seatClass: 'B' },
      { code: 'Q8', seatClass: 'B' },
      { code: 'Q9', seatClass: 'B' },
      { code: 'Q10', seatClass: 'B' },
      { code: 'Q11', seatClass: 'B' },
      { code: 'Q12', seatClass: 'B' },
      { code: 'Q13', seatClass: 'B' },
      { code: 'Q14', seatClass: 'B' },
      { code: 'Q15', seatClass: 'B' },
      { code: 'BLOCK' },
      { code: 'BLOCK' },
    ],
  ];
